
columns = {
    'subjects': [
        'age_in_years',
        'arv_clinic',
        'cd4_date',
        'cd4_tested',
        'cd4_value',
        'circumcised',
        'community',
        'consent_date',
        'final_arv_status',
        'final_hiv_status',
        'gender',
        'identity',
        'identity256',
        'pregnant',
        'prev_result',
        'prev_result_date',
        'prev_result_known',
        'referred',
        'self_reported_result',
        'subject_identifier',
        'survey',
        'timestamp',
    ],
    'members': [
        'able_to_participate',
        'age_in_years',
        'community',
        'enrolled',
        'gender',
        'household_identifier',
        'plot_identifier',
        'survey',
    ],
    'households': [
        'community',
        'enrolled',
        'enumerated',
        'household_identifier',
        'plot_identifier',
        'survey',
    ],
    'plots': [
        'community',
        'confirmed',
        'enrolled',
        'plot_identifier',
        'plot_status',
    ],
}
