

columns = {
    'subjects': [
        'age_in_years',
        'arv_clinic',
        'cd4_date',
        'cd4_tested',
        'cd4_value',
        'circumcised',
        'community',
        'consent_date',
        'final_arv_status',
        'final_hiv_status',
        'gender',
        'identity',
        'identity256',
        'pregnant',
        'prev_result',
        'prev_result_date',
        'prev_result_known',
        'referred',
        'self_reported_result',
        'subject_identifier',
        'survey',
        'timestamp',
        'vl_drawn_date'
    ],
    'members': [
        'able_to_participate',
        'age_in_years',
        'community',
        'enrolled',
        'gender',
        'household_identifier',
        'member_modified',
        'plot_identifier',
        'registered_subject',
        'study_resident',
        'survey',
        'survival_status',
    ],
    'households': [
        'community',
        'confirmed',
        'enrolled',
        'enumerated',
        'household_identifier',
        'household_modified',
        'plot_identifier',
        'survey',
    ],
    'plots': [
        'community',
        'confirmed',
        'enrolled',
        'plot_identifier',
        'plot_modified',
        'plot_status',
        'selected',
    ],
}
